### ISSUE TITLE
Vectorized indexing

### ISSUE THREAD

**Issue by Zetison** [sintefore/TimeStruct.jl#12]
It would be nice if TimeStruct could enable vectorized indices, i.e.:
```
function Base.getindex(rp::RepresentativeProfile, indices::Vector{T}) where {T <: TS.TimePeriod}
    return [rp[i] for i in indices]
end
```
And correspondingly for the other profiles. Having a vector of TimePeriod (call it `indices`) would then enable simple extracting of multiple values of a TimeProfile (call it `data`) of the form `data[indices]`. This is nice if `indices` is reused and it would then simplify the code. For example, when plotting data, the x-axis data (time values) may be the same for a multiple time series, and enabling vectorized indexing would simplify the code greatly.

**Comment by JulStraus** [comment]
Alternatively, it could be also interesting to have an approach like

```julia
function Base.getindex(rp::RepresentativeProfile, ts::TimeStructure)
    return [rp[i] for t in ts]
end
```

This approach would be more generic and would avoid the requirement to create all individual operational periods. Instead, it is purely based on the chosen `TimeStructure`.

**Comment by trulsf** [comment]
I am a bit skeptical about using `getindex` in a sligthly non-standard way. What about a solution based on broadcasting? If we define 
```julia
value(profile::TimeProfile) = Base.Fix1(getindex, profile)
```
then you can get the functionality required in a flexible manner using broadcasting
```julia
vals = value(profile).(ts)
```

**Comment by hellemo** [comment]
I like the idea of providing `getindex` for subsets of `TimePeriods` as this kind of indexing is quite common for linear indexing and is easier to read than the `value` function suggested by @trulsf .

The documentation for `getindex` mentions `getindex(collection, key...)` , so how about supporting:
```julia
 Base.getindex(TP::TimeProfile, inds...) = [TP[i] for i in inds]

# Example
 fp = FixedProfile(100)
 sp = StrategicProfile([1,2,3,4,5])
 ts = TwoLevel(4, 1, SimpleTimes(24, 1))
indices = [ts...][[1,39]]

fp[indices...]
#=2-element Vector{Int64}:
 100
 100
=#
sp[indices...]
#=2-element Vector{Int64}:
 1
 2
=#

sp[ts...]
#=
96-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
=#
```

It would be nice to be able to also do
```julia
 Base.getindex(TP::TimeProfile, inds::Vector{T}) where {T<:TimeStruct.TimePeriod} = [TP[i] for i in inds]
```
but this seems to give method ambiguity, meaning we need to go back to the suggestion by @Zetison

**Comment by JulStraus** [comment]
> It would be nice to be able to also do
> 
> ```julia
>  Base.getindex(TP::TimeProfile, inds::Vector{T}) where {T<:TimeStruct.TimePeriod} = [TP[i] for i in inds]
> ```
> 
> but this seems to give method ambiguity, meaning we need to go back to the suggestion by @Zetison

Wouldn't be here the solution to modify the existing functions for `getindex`? Currently, we allow in the [latest PR](https://github.com/sintefore/TimeStruct.jl/pull/9):

1. `FixedProfile` any input,
2. `OperationalProfile` either a `TimePeriod` or providing an error,
3. `StrategicProfile` either a `TimePeriod` or anything with an error, if it is not possible to deduce the strategic period,
4. `ScenarioProfile`  either a `TimePeriod` or anything with an error, if it is not possible to deduce the operational scenario, and
5. `RepresentativeProfile`  either a `TimePeriod` or anything with an error, if it is not possible to deduce the representative period.

All of these calls are essentially requiring that a function should not be an `Array` while the functions without a type just postpone the error calling. That implies to my understanding that we can essentially limit the error functions to a subset of `TimeStructure` and `TimePeriod`, i.e., as:

```julia
function Base.getindex(sp::StrategicProfile, period::T) where {T<:Union{TimePeriod, TimeStructure}
    return _value_lookup(StrategicIndexable(T), sp, period)
end

# instead of 
function Base.getindex(sp::StrategicProfile, period::T) where {T}
    return _value_lookup(StrategicIndexable(T), sp, period)
end
```

We can then have two high level functions given as 
```julia
 Base.getindex(TP::TimeProfile, inds::Vector{T}) where {T<:Union{TimePeriod, TimeStructure} = [TP[i] for i in inds]

 Base.getindex(TP::TimeProfile, inds::Any)  = @error("Type $(typeof(inds)) can not be used as index for a $(typeof(TP))")
```

This still allows us to differentiate between wrong access *via* `AbstractRepresentativePeriod` for an `OperationalProfile` and entirely wrong indices like "String".

**Comment by JulStraus** [comment]
> I think the approach suggested by @JulStraus will work. To avoid method ambiguity the `getindex` functions of `FixedProfile` and `OperationalProfile` also have to be parameterized by type.

Yeah, that should be implemented for all.

**Comment by trulsf** [comment]
The functionality is added as part of the work in PR #9
