### ISSUE TITLE
Move support for Unitful to extension?

### ISSUE THREAD

**Issue by hellemo** [sintefore/TimeStruct.jl#13]
While support for Unitful is very nice, we often don't use it, so would it be more appropriate to move it to an extension to lighten the dependencies?

**Comment by trulsf** [comment]
I tested it once and it was mostly fairly trivial to do, but i had some issues with the current definition of  `Duration` which is now 
```julia
# Durations can be provided as real numbers or as a Quantity with time dimension
Duration = Union{Real,Unitful.Quantity{V,Unitful.𝐓} where {V}}
```
Now I do not think this is crucial to keep. It just restricts the duration to have time dimension if using units, and is not required for any functionality. Letting `Duration = Number` would then work.

**Comment by hellemo** [comment]
I see. That is a nice feature, but I think I still lean towards reducing the number of dependencies.
I tried to think of a workaround, but since type definitions depend on Unitful, I don't see how it can be done.

**Comment by trulsf** [comment]
Added as part of PR #15
