### ISSUE TITLE
Field of composite types, functions for accessing these, and incorporated parametric types

### ISSUE THREAD

**Issue by JulStraus** [sintefore/TimeStruct.jl#27]
So far, we are not entirely consistent in the individual composite types and their fields. I partly updated these in #23, although there are still some inconsistencies.

The most relevant I can see are:

- [ ] Unify the structure of all `TimePeriod`s, _i.e._, always have `per` as last argument.
- [ ] Make `OperationalPeriod` parametric as all other `TimePeriod`s.
- [ ] Unify the names of the individual types: So far, we have frequently `OpScenario` and `OperationalScenario`, depending on the other included types. I would opt for `OpScenario` or even `OpScen` although the latter could lead to confusions with `OpScens` (The same holds for `ReprPeriods` and `ReprPeriod`.
- [ ] Introduce an abstract supertype for the likes of `StratReprPeriods`, `ReprOperationalScenario`, and so on, that is all except for the lowest level. This would allow us to reuse a significant number of code lines in the iterator and last functions.

There are potentially a large fraction of additional things one could do, but these are the once coming directly to mind.

**Comment by trulsf** [comment]
Good points. I agree with using `OpScenario`.
