### ISSUE TITLE
Probabilities and multiples

### ISSUE THREAD

**Issue by trulsf** [sintefore/TimeStruct.jl#28]
With the strategic uncertainty in place, I think there is a need to separate between the probability of a scenario occurring as part of the overall tree (`probability`) and the probability of the scenario as part of `OperationalScenarios`. My suggestion is to add a `probabilty_scen` similar to `probability_branch`.

We should also consider whether to export `mult_repr` and `mult_scen` and ensure that they are available for all relevant structures.

**Comment by JulStraus** [comment]
I agree that it can be beneficial to introduce a `probability_scen` in addition as well as export `mult_repr` and `mult_scen`. Both can be useful within the application.

**Comment by trulsf** [comment]
Fixed by #30
