### ISSUE TITLE
Prepare for JOSS submission

### ISSUE THREAD

**Issue by trulsf** [sintefore/TimeStruct.jl#34]
This issue is created to track things needed to be done before submitting a paper on `TimeStruct` to the Journal of Open Source Software after the release of a feature complete version 0.9.

Things to be completed:
- [x] Create a new branch for the submission with a skeleton for the paper.md file 
- [x] Write the contents of the paper.md
- [x] Add a note on how to contribute in the documentation
- [x] Include strategic trees with examples in the documentation
- [x] Check that we meet all [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html)

**Comment by JulStraus** [comment]
I think I can work on the documentation, at leas the how-to Section. My aim is to base it quite heavily on EMX, although it requires changes due to a different contribution we may ask fo.

**Comment by hellemo** [comment]
Branch with skeleton here: https://github.com/sintefore/TimeStruct.jl/tree/joss_submission
